# type: ignore
import os
import shutil
import subprocess

from conan import ConanFile
from conan.errors import ConanInvalidConfiguration
from conan.tools.build import check_min_cppstd
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake, cmake_layout
from conan.tools.files import copy, rename, replace_in_file, rm, rmdir
from conan.tools.scm import Git


class LibTorchRecipe(ConanFile):
    name = "libtorch"

    description = "LibTorch: the C++ API of PyTorch"
    license = "BSD-3-Clause"
    url = "https://github.com/parantapa/pb-conan-index"
    homepage = "https://pytorch.org/cppdocs"
    topics = (
        "machine-learning",
        "deep-learning",
        "tensor",
        "autograd",
        "neural-network",
    )

    package_type = "library"
    implements = ["auto_shared_fpic"]
    settings = "os", "compiler", "build_type", "arch"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "with_openmp": [True, False],
        "with_cuda": [True, False],
        "with_mkldnn": [True, False],
    }
    default_options = {
        "shared": True,
        "fPIC": True,
        "with_openmp": True,
        "with_cuda": False,
        "with_mkldnn": False,
    }

    def requirements(self):
        self.requires("eigen/5.0.1")

    def validate(self):
        check_min_cppstd(self, 20)

        if self.settings.os not in ["Linux", "FreeBSD", "Macos"]:
            raise ConanInvalidConfiguration(
                f"{self.ref} is only set up for Linux, FreeBSD and macOS"
            )

        if self.options.with_cuda and self.settings.os != "Linux":
            raise ConanInvalidConfiguration(
                f"{self.ref}:with_cuda=True is only set up for Linux"
            )

    @property
    def _codegen_modules(self):
        return ["yaml", "typing_extensions"]

    def validate_build(self):
        python = shutil.which("python3") or shutil.which("python")
        if python is None:
            raise ConanInvalidConfiguration(
                "Building libtorch needs a python interpreter on PATH; "
                "the ATen sources are generated by torchgen at build time"
            )

        missing = []
        for module in self._codegen_modules:
            probe = subprocess.run(
                [python, "-c", f"import {module}"],
                capture_output=True,
            )
            if probe.returncode != 0:
                missing.append(module)
        if missing:
            raise ConanInvalidConfiguration(
                f"{python} is missing the modules torchgen imports: "
                f"{', '.join(missing)}. Install them with "
                f"pip install {' '.join(missing)}"
            )

    _submodules = (
        "third_party/FP16",
        "third_party/cpp-httplib",
        "third_party/cpuinfo",
        "third_party/flatbuffers",
        "third_party/fmt",
        "third_party/kineto",
        "third_party/nlohmann",
        "third_party/onnx",
        "third_party/protobuf",
        "third_party/psimd",
        "third_party/sleef",
    )

    _cuda_submodules = (
        "third_party/NVTX",
        "third_party/cudnn_frontend",
        "third_party/cutlass",
    )

    # The submodule with_mkldnn needs.
    # ideep is the wrapper ATen includes,
    # and it carries oneDNN itself as a submodule of its own
    # under mkl-dnn, which is where FindMKLDNN.cmake looks for it,
    # so this one is checked out recursively.
    # source() cannot read options here either.
    _mkldnn_submodules = ("third_party/ideep",)

    def source(self):
        source = self.conan_data["sources"][self.version]

        git = Git(self)
        git.clone(
            url=source["url"],
            target=".",
            args=["--branch", source["tag"], "--depth", "1"],
        )

        submodules = self._submodules + self._cuda_submodules
        git.run("submodule update --init --depth 1 -- " + " ".join(submodules))

        git.run(
            "submodule update --init --depth 1 --recursive -- "
            + " ".join(self._mkldnn_submodules)
        )

        self._patch_sources()

    def _patch_sources(self):
        replace_in_file(
            self,
            os.path.join(self.source_folder, "cmake", "PreBuildSteps.cmake"),
            "if(NOT DEFINED USE_SYSTEM_LIBS OR NOT USE_SYSTEM_LIBS)",
            "if(FALSE)  # conan fetches the submodules it needs in source()",
        )

    def layout(self):
        cmake_layout(self, src_folder="pytorch")

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()

        tc = CMakeToolchain(self)

        tc.cache_variables["BUILD_PYTHON"] = False
        tc.cache_variables["BUILD_TEST"] = False
        tc.cache_variables["BUILD_BINARY"] = False
        tc.cache_variables["ATEN_NO_TEST"] = True
        tc.cache_variables["INSTALL_TEST"] = False
        tc.cache_variables["BUILD_AOT_INDUCTOR_TEST"] = False
        tc.cache_variables["BUILD_STATIC_RUNTIME_BENCHMARK"] = False
        tc.cache_variables["BUILD_MOBILE_BENCHMARK"] = False
        tc.cache_variables["BUILD_MOBILE_TEST"] = False
        tc.cache_variables["BUILD_JNI"] = False
        tc.cache_variables["BUILD_LITE_INTERPRETER"] = False
        tc.cache_variables["BUILD_LAZY_TS_BACKEND"] = False

        # ---- accelerators
        # The CUDA toolkit and cuDNN are taken from the build machine.
        cuda = bool(self.options.with_cuda)

        tc.cache_variables["USE_CUDA"] = cuda
        tc.cache_variables["USE_CUDNN"] = cuda

        tc.cache_variables["USE_CUSPARSELT"] = False
        tc.cache_variables["USE_CUDSS"] = False
        tc.cache_variables["USE_MAGMA"] = False
        tc.cache_variables["USE_CUFILE"] = False
        tc.cache_variables["USE_ROCM"] = False
        tc.cache_variables["USE_XPU"] = False
        tc.cache_variables["USE_MTIA"] = False
        tc.cache_variables["USE_MPS"] = False
        tc.cache_variables["USE_VULKAN"] = False
        tc.cache_variables["USE_PYTORCH_METAL"] = False
        tc.cache_variables["USE_PYTORCH_METAL_EXPORT"] = False
        tc.cache_variables["USE_COREML_DELEGATE"] = False
        tc.cache_variables["USE_FLASH_ATTENTION"] = False
        tc.cache_variables["USE_MEM_EFF_ATTENTION"] = False

        # MSLK turns itself on for a CUDA build that targets SM100a,
        # and its vendored source tree is not one source() fetches.
        tc.cache_variables["USE_MSLK"] = False

        # ---- distributed
        tc.cache_variables["USE_DISTRIBUTED"] = False
        tc.cache_variables["USE_MPI"] = False
        tc.cache_variables["USE_GLOO"] = False
        tc.cache_variables["USE_TENSORPIPE"] = False
        tc.cache_variables["USE_NCCL"] = False
        tc.cache_variables["USE_XCCL"] = False
        tc.cache_variables["USE_UCC"] = False

        # ---- optional CPU kernel libraries.
        tc.cache_variables["USE_FBGEMM"] = False
        tc.cache_variables["USE_NNPACK"] = False
        tc.cache_variables["USE_QNNPACK"] = False
        tc.cache_variables["USE_PYTORCH_QNNPACK"] = False
        tc.cache_variables["USE_XNNPACK"] = False
        tc.cache_variables["USE_MKLDNN"] = bool(self.options.with_mkldnn)
        tc.cache_variables["USE_KLEIDIAI"] = False
        tc.cache_variables["USE_MIMALLOC"] = False

        # ---- profiling and instrumentation
        tc.cache_variables["USE_KINETO"] = False
        tc.cache_variables["USE_ITT"] = False
        tc.cache_variables["USE_VALGRIND"] = False
        tc.cache_variables["USE_CPP_CODE_COVERAGE"] = False

        # ---- host integration this package has no use for
        tc.cache_variables["USE_NUMPY"] = False
        tc.cache_variables["USE_NUMA"] = False
        tc.cache_variables["USE_GFLAGS"] = False
        tc.cache_variables["USE_GLOG"] = False
        tc.cache_variables["USE_CCACHE"] = False

        tc.cache_variables["USE_OPENMP"] = bool(self.options.with_openmp)

        tc.cache_variables["BLAS"] = "MKL"
        tc.cache_variables["USE_STATIC_MKL"] = False

        tc.cache_variables["USE_SYSTEM_EIGEN_INSTALL"] = True

        # GNUInstallDirs picks lib64 on 64 bit non-Debian Linux,
        # which would put the libraries outside the directories
        # this recipe reports to consumers.
        tc.cache_variables["CMAKE_INSTALL_LIBDIR"] = "lib"

        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    # The only directories of the install tree this package keeps.
    _package_roots = ("include", "lib", "licenses", "share")

    def package(self):
        copy(
            self,
            "LICENSE",
            src=self.source_folder,
            dst=os.path.join(self.package_folder, "licenses"),
        )
        copy(
            self,
            "NOTICE",
            src=self.source_folder,
            dst=os.path.join(self.package_folder, "licenses"),
        )

        cmake = CMake(self)
        cmake.install()

        for entry in os.listdir(self.package_folder):
            if entry in self._package_roots:
                continue
            path = os.path.join(self.package_folder, entry)
            if os.path.isdir(path):
                rmdir(self, path)
            else:
                os.remove(path)

        rm(self, "*.a", os.path.join(self.package_folder, "lib"))
        rm(self, "libtorch_global_deps.*", os.path.join(self.package_folder, "lib"))
        rmdir(self, os.path.join(self.package_folder, "lib", "pkgconfig"))
        rmdir(self, os.path.join(self.package_folder, "lib", "cmake"))

        # The install tree carries the cmake package files of the vendored
        # dependencies next to torch's own; conan generates its own.
        rename(
            self,
            os.path.join(self.package_folder, "share", "cmake"),
            os.path.join(self.package_folder, "share", "_orig_cmake"),
        )

    def package_info(self):
        if self.options.with_cuda:
            self.cpp_info.libs = [
                "torch",
                "torch_cuda",
                "torch_cpu",
                "c10_cuda",
                "c10",
            ]
        else:
            self.cpp_info.libs = ["torch", "torch_cpu", "c10"]

        self.cpp_info.includedirs = [
            "include",
            os.path.join("include", "torch", "csrc", "api", "include"),
        ]

        if self.settings.os in ["Linux", "FreeBSD"]:
            self.cpp_info.system_libs = ["m", "dl", "pthread", "rt"]

            # libtorch is a shim: it carries a DT_NEEDED on torch_cpu, c10
            # and, with CUDA, on torch_cuda and c10_cuda, and no code of its
            # own that a consumer would reference. The linker default of
            # --as-needed therefore drops it, and everything reachable only
            # through it goes with it. What that costs is the registration
            # that runs from static initializers: with torch_cuda dropped the
            # CUDA hooks are never installed and torch::cuda::is_available()
            # answers false on a machine with a working GPU.
            # Upstream hits this too and force links the same way,
            # in the torch target of its own Caffe2Targets.cmake.
            if self.options.shared:
                torch_library = os.path.join(self.package_folder, "lib", "libtorch.so")
                # One flag per list entry:
                # a single string is passed to the linker as one argument.
                force_link = [
                    f"-Wl,--no-as-needed,{torch_library}",
                    "-Wl,--as-needed",
                ]
                self.cpp_info.exelinkflags = force_link
                self.cpp_info.sharedlinkflags = force_link

        self.cpp_info.set_property("cmake_file_name", "Torch")
        self.cpp_info.set_property("cmake_target_name", "torch")
